//
//  AppLanguageManager.swift
//  LiberEye
//
//  Shared English interface copy.
//

import Foundation
import Combine

enum AppLanguage: String, CaseIterable, Identifiable {
    case en = "en"

    var id: String { rawValue }
    var displayName: String { "English" }
}

@MainActor
final class AppLanguageManager: ObservableObject {
    static let shared = AppLanguageManager()

    @Published var currentLanguage: AppLanguage = .en

    private init() {}

    func text(_ key: String) -> String {
        Self.copy[key] ?? key
    }

    func format(_ key: String, _ arguments: CVarArg...) -> String {
        String(format: text(key), locale: Locale(identifier: "en_US"), arguments: arguments)
    }

    private static let copy: [String: String] = [
        "app_started": "LiberEye is ready",
        "cloud_service": "LiberEye Cloud",
        "cloud_enabled": "Enable cloud analysis",
        "cloud_address": "Server URL",
        "cloud_token": "Access token",
        "cloud_enter_token": "Enter the server access token",
        "cloud_connection_status": "Service status",
        "cloud_save": "Save settings",
        "cloud_test": "Test service",
        "cloud_testing": "Checking service...",
        "cloud_not_tested": "Not tested",
        "cloud_model_ready": "Model service ready",
        "cloud_basic_ready": "Basic mode ready",
        "cloud_basic_note": "The server is in basic mode with no vision models enabled.",
        "cloud_settings_footer": "Enter the HTTPS URL and access token of your LiberEye server. The example domain is a placeholder, not an online service. Save settings now and test once your server is deployed.",
        "cloud_setup_required": "Set up cloud analysis",
        "cloud_setup_description": "Enter your LiberEye server URL and access token in Settings. Quick OCR remains available offline.",
        "cloud_disabled": "Cloud analysis is off",
        "cloud_disabled_description": "Enable LiberEye Cloud in Settings to analyze your surroundings.",
        "optional_services": "Optional services",
        "cloudbase_optional": "Optional account service",
        "cloudbase_optional_note": "Account service settings are separate from phone capture, offline OCR and LiberEye Cloud analysis.",
        "direct_vision_optional": "Optional image and chat service",
        "direct_vision_note": "Used for manual image analysis when LiberEye Cloud is disabled, and general voice questions. Cloud navigation does not require these settings.",
        "glasses_unavailable": "This build uses the phone camera",
        "glasses_unavailable_note": "Glasses require a LiberEye build with glasses support. Band connection and phone capture remain available.",
        "connect_glasses_first": "Connect glasses first",
        "band_scan_status": "Band Bluetooth status",
        "scan_bands": "Scan bands",
        "cloud_result": "Scene analysis result",
        "cloud_priority_danger": "Danger",
        "cloud_priority_warn": "Caution",
        "cloud_priority_normal": "Context",
        "settings": "Settings",
        "navigation": "Navigation",
        "obstacle_detection": "Obstacle",
        "scene_analysis": "Scene Analysis",
        "device_manager": "Devices",
        "bracelet": "Band",
        "speaking": "Speaking",
        "connected": "Connected",
        "disconnected": "Disconnected",
        "connecting": "Connecting...",
        "unknown": "Unknown",
        "unbound": "Unbound",
        "disconnecting": "Disconnecting",
        "scanning": "Scanning...",
        "safe": "Safe",
        "caution": "Caution",
        "warning": "Warning",
        "danger": "Danger",
        "critical": "Critical",
        "glasses": "Glasses",
        "phone_camera": "Phone Camera",
        "vibration_bracelet": "Vibration Band",
        "glasses_mode_desc": "Use glasses to capture environment information",
        "phone_mode_desc": "Use the phone camera for perception",
        "speak_status": "Speak Status",
        "simulate_data": "Simulate",
        "describe_view": "Describe",
        "describing_view": "Describing the current view",
        "photo_failed": "Photo failed",
        "assistant_awake": "I'm listening",
        "assistant_thinking": "Thinking",
        "capturing": "Capturing",
        "timed_capture": "Timed",
        "live": "Live",
        "obstacle_detected": "Obstacle detected",
        "direction": "Direction",
        "distance": "Distance",
        "type": "Type",
        "glasses_timed_capture": "Timed glasses capture",
        "waiting_for_glasses": "Waiting for glasses",
        "switch_to_glasses_to_start": "Switch to glasses mode to start",
        "capturing_glasses_photo": "Capturing glasses photo...",
        "last_capture_seconds": "Last capture: %d seconds ago, every %d seconds",
        "capture_without_api": "Configure LiberEye Cloud to capture and analyze automatically.",
        "waiting_next_capture": "Waiting for next capture, every %d seconds",
        "captured_configure_api": "Photo captured. Configure LiberEye Cloud to analyze automatically.",
        "analysis_busy_skip": "Previous image analysis is still running; skipping this round",
        "analyzing_glasses_photo": "Analyzing glasses photo...",
        "timed_analysis_complete": "Timed analysis complete",
        "just_now": "Just now",
        "seconds_ago": "%d seconds ago",
        "minutes_ago": "%d minutes ago",
        "scene_description": "Scene",
        "text_recognition": "Text",
        "store_recognition": "Store",
        "obstacle_analysis": "Obstacle",
        "full_analysis": "Full Analysis",
        "analysis_mode": "Analysis Mode",
        "need_doubao_api": "Image analysis setup required",
        "need_doubao_api_desc": "Enter an image service API Key in Settings to enable image analysis",
        "take_photo_analysis": "Phone Camera",
        "choose_from_album": "Album",
        "quick_ocr": "Quick OCR",
        "analyze_glasses_frame": "Glasses Camera",
        "clear": "Clear",
        "reanalyze": "Analyze Again",
        "result_suffix": "Result",
        "voice_result": "Speak Result",
        "recognized_text": "Recognized Text",
        "analysis_result": "Analysis result",
        "speak_recognized_text": "Speak recognized text",
        "no_text_recognized": "No text recognized",
        "no_glasses_frame": "No glasses image available",
        "usage_tips": "Tips",
        "analyzing": "Analyzing...",
        "ocr_running": "Recognizing text...",
        "please_wait": "Please wait",
        "tip_store": "Point at a storefront sign to read its name and type",
        "tip_text": "Point at documents or menus to recognize text",
        "tip_obstacle": "Use Obstacle mode at intersections or unfamiliar places",
        "tip_quick_ocr": "Quick OCR works offline for fast text reading",
        "cloudbase_service": "CloudBase",
        "cloudbase_status": "CloudBase Status",
        "not_configured": "Not configured",
        "connected_status": "Connected",
        "connection_failed": "Connection failed",
        "env_id": "Environment ID",
        "enter_env_id": "Enter CloudBase environment ID",
        "enter_publishable_key": "Enter Publishable Key",
        "save_connect": "Save and Connect",
        "logged_in_phone": "Signed in (phone)",
        "logged_in_guest": "Signed in (guest)",
        "logout": "Log out",
        "login_cloudbase": "Sign in to CloudBase",
        "cloudbase_footer": "Create a CloudBase environment in Tencent Cloud, then paste the Environment ID and Publishable Key here.",
        "doubao_config": "Doubao service",
        "doubao_footer": "Get an API Key from Volcengine Ark and choose a vision-capable model such as doubao-seed-1-6-flash-250828.",
        "enter_doubao_key": "Enter Doubao API Key",
        "model_id": "Model ID",
        "save_api_config": "Save API Settings",
        "saved": "Saved",
        "voice_settings": "Voice",
        "auto_obstacle_voice": "Auto speak obstacle alerts",
        "speech_rate": "Speech rate",
        "current_percent": "Current: %.0f%%",
        "voice_threshold": "Alert threshold",
        "caution_above": "Caution and above",
        "warning_above": "Warning and above",
        "danger_above": "Danger and above",
        "enable_bracelet_vibration": "Enable bracelet vibration",
        "no_vibration": "No vibration",
        "light_interval_vibration": "Light intermittent vibration",
        "medium_interval_vibration": "Medium intermittent vibration",
        "rapid_vibration": "Rapid vibration",
        "continuous_emergency_vibration": "Continuous emergency vibration",
        "glasses_timed_analysis": "Timed glasses analysis",
        "glasses_analysis_interval": "Analyze one photo every %.0f seconds",
        "five_seconds_fast": "5 s (faster)",
        "sixty_seconds_quiet": "60 s (quieter)",
        "glasses_timed_analysis_running": "Timed analysis running",
        "glasses_timed_analysis_waiting": "Timed analysis enabled",
        "glasses_timed_analysis_need_api": "Configure LiberEye Cloud to enable timed analysis",
        "alert_distance": "Obstacle alert distance: %.1f m",
        "one_meter_near": "1 m (near)",
        "five_meter_far": "5 m (far)",
        "connected_devices": "Connected Devices",
        "found_heyc_glasses": "Found HeyCyan Glasses",
        "found_bracelets": "Found Bands",
        "bracelet_vibration_test": "Band Vibration Test",
        "perception_mode": "Perception Mode",
        "stop_scanning": "Stop Scan",
        "scan_devices": "Scan Devices",
        "bluetooth_enabled": "Bluetooth enabled",
        "bluetooth_disabled": "Bluetooth disabled",
        "disconnect": "Disconnect",
        "connect_band": "Connect LiberEye Band",
        "connected_name": "Connected %@",
        "connected_finding_vibration": "Connected %@, finding vibration service",
        "scanning_nearby": "Scanning nearby devices...",
        "unknown_device": "Unknown Device",
        "unknown_glasses": "Unknown Glasses",
        "tap_connect_band": "Tap to connect LiberEye band",
        "tap_to_connect": "Tap to connect",
        "level_vibration": "%@ vibration",
        "current_mode": "Current Mode",
        "glasses_mode_note": "Glasses mode: obstacle data comes from the glasses. The phone camera is off.",
        "phone_mode_note": "Phone mode: use the phone camera for perception when glasses are unavailable.",
        "test_voice": "Test voice",
        "about": "About",
        "version": "Version",
        "developer": "Developer",
        "doubao_website": "Doubao website",
        "api_saved_voice": "API settings saved",
        "cloudbase_connected_voice": "CloudBase connected",
        "cloudbase_failed_voice": "CloudBase connection failed. Please check settings.",
        "north": "N",
        "northeast": "NE",
        "east": "E",
        "southeast": "SE",
        "south": "S",
        "southwest": "SW",
        "west": "W",
        "northwest": "NW",
        "facing_direction": "Facing %@",
        "walking_speed": "Walking speed %.1f m/s",
        "speak_direction": "Speak direction",
        "heading_accessibility": "Current heading %@, %d degrees",
        "current_location": "Current Location",
        "locating": "Locating",
        "not_located": "Not Located",
        "latitude": "Latitude",
        "longitude": "Longitude",
        "accuracy": "Accuracy",
        "location_map": "Location Map",
        "speak_full_location": "Speak full location",
        "speak_location_accessibility": "Speak current location and heading",
        "speak_heading_with_vibration": "Speak heading with band vibration",
        "speak_heading_accessibility": "Speak heading and trigger band vibration",
        "getting_location": "Getting location...",
        "navigation_accessibility": "Navigation, view current location and heading",
        "obstacle_accessibility": "Obstacle detection and perception status",
        "scene_analysis_accessibility": "Scene Analysis, scan text and scenes",
        "device_manager_accessibility": "Devices, manage Bluetooth glasses and band",
        "settings_accessibility": "Settings, adjust app options"
    ]
}
